const bd_locations = [
  {
    query: "162.208.16.76",
    status: "success",
    continent: "North America",
    continentCode: "NA",
    country: "Canada",
    countryCode: "CA",
    region: "QC",
    regionName: "Quebec",
    city: "Montreal",
    district: "",
    zip: "H3H",
    lat: 45.5075,
    lon: -73.5887,
    timezone: "America/Toronto",
    offset: -18000,
    currency: "CAD",
    isp: "MEGA Cloud Services Limited",
    org: "MEGA Cloud Services Limited",
    as: "AS205809 MEGA Cloud Services Limited",
    asname: "MEGA",
    mobile: false,
    proxy: true,
    hosting: false,
  },

  {
    query: "185.206.25.111",
    status: "success",
    continent: "North America",
    continentCode: "NA",
    country: "Canada",
    countryCode: "CA",
    region: "BC",
    regionName: "British Columbia",
    city: "Vancouver",
    district: "",
    zip: "V5Z",
    lat: 49.2476,
    lon: -123.1234,
    timezone: "America/Vancouver",
    offset: -28800,
    currency: "CAD",
    isp: "MEGA Cloud Services Limited",
    org: "Mega",
    as: "AS205809 MEGA Cloud Services Limited",
    asname: "MEGA",
    mobile: false,
    proxy: true,
    hosting: false,
  },

  {
    query: "149.34.250.181",
    status: "success",
    continent: "North America",
    continentCode: "NA",
    country: "United States",
    countryCode: "US",
    region: "FL",
    regionName: "Florida",
    city: "Miami",
    district: "",
    zip: "33197",
    lat: 25.7701,
    lon: -80.1928,
    timezone: "America/New_York",
    offset: -18000,
    currency: "USD",
    isp: "Datacamp Limited",
    org: "Datacamp Limited",
    as: "AS212238 Datacamp Limited",
    asname: "CDNEXT",
    mobile: false,
    proxy: false,
    hosting: true,
  },

  {
    query: "38.253.137.2",
    status: "success",
    continent: "South America",
    continentCode: "SA",
    country: "Peru",
    countryCode: "PE",
    region: "LMA",
    regionName: "Lima Province",
    city: "Lima",
    district: "",
    zip: "",
    lat: -12.046,
    lon: -77.0305,
    timezone: "America/Lima",
    offset: -18000,
    currency: "PEN",
    isp: "Wi-net Telecom S.A.C.",
    org: "WI-NET Telecom SAC",
    as: "AS265691 WI-NET TELECOM S.A.C.",
    asname: "WI-NET TELECOM S.A.C.",
    mobile: false,
    proxy: false,
    hosting: false,
  },
];
