export const bd_location = [
  {
    asn: "AS812",
    city: "Vancouver",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "24.114.0.1",
    languages: "en-CA,fr-CA",
    latitude: 49.2827,
    longitude: -123.1207,
    network: "24.114.0.0/16",
    org: "TELUS Communications",
    postal: "V6B",
    region: "British Columbia",
    region_code: "BC",
    timezone: "America/Vancouver",
    utc_offset: "-0700",
    version: "IPv4",
  },

  {
    asn: "AS5769",
    city: "Montreal",
    continent_code: "NA",
    country: "CA",
    country_area: 9984670,
    country_calling_code: "+1",
    country_capital: "Ottawa",
    country_code: "CA",
    country_code_iso3: "CAN",
    country_name: "Canada",
    country_population: 38008005,
    country_tld: ".ca",
    currency: "CAD",
    currency_name: "Canadian Dollar",
    in_eu: false,
    ip: "142.114.0.1",
    languages: "fr-CA,en-CA",
    latitude: 45.5017,
    longitude: -73.5673,
    network: "142.114.0.0/16",
    org: "Bell Canada",
    postal: "H1A",
    region: "Quebec",
    region_code: "QC",
    timezone: "America/Toronto",
    utc_offset: "-0500",
    version: "IPv4",
  },

  {
    asn: "AS7018",
    city: "Miami",
    continent_code: "NA",
    country: "US",
    country_area: 9833517,
    country_calling_code: "+1",
    country_capital: "Washington, D.C.",
    country_code: "US",
    country_code_iso3: "USA",
    country_name: "United States",
    country_population: 331893745,
    country_tld: ".us",
    currency: "USD",
    currency_name: "US Dollar",
    in_eu: false,
    ip: "45.57.0.1",
    languages: "en-US,es-US",
    latitude: 25.7617,
    longitude: -80.1918,
    network: "45.57.0.0/16",
    org: "AT&T Services",
    postal: "33101",
    region: "Florida",
    region_code: "FL",
    timezone: "America/New_York",
    utc_offset: "-0500",
    version: "IPv4",
  },

  {
  asn: "AS1136",
  city: "Amsterdam",
  continent_code: "EU",
  country: "NL",
  country_area: 41543,
  country_calling_code: "+31",
  country_capital: "Amsterdam",
  country_code: "NL",
  country_code_iso3: "NLD",
  country_name: "Netherlands",
  country_population: 17590672,
  country_tld: ".nl",
  currency: "EUR",
  currency_name: "Euro",
  in_eu: true,
  ip: "145.0.0.1",
  languages: "nl-NL,en",
  latitude: 52.3676,
  longitude: 4.9041,
  network: "145.0.0.0/16",
  org: "KPN B.V.",
  postal: "1011",
  region: "North Holland",
  region_code: "NH",
  timezone: "Europe/Amsterdam",
  utc_offset: "+0200",
  version: "IPv4",
}

];
